firewalls:
  main:
    pattern: "^/"
    auth:
      bearer:
        enabled: false

access:
  - path: /csrf-token
    require: IS_AUTHENTICATED_ANONYMOUSLY
  - path: /form
    require: IS_AUTHENTICATED_ANONYMOUSLY
  - path: /*
    require: AUTH_REQUIRED

csrf:
  enabled: true
  secret: "your-32-byte-csrf-secret-here!!!!"
  secure: true
  same_site: "Lax"
  field_name: "csrf_token"
  header_name: "X-CSRF-Token"
