routes:
  - path: /
    method: [GET]
    handler: Home.GET
    require: IS_AUTHENTICATED_ANONYMOUSLY

  - path: /login
    method: [GET, POST]
    handlers:
      GET: Auth.GET
      POST: Auth.POST
    require: IS_AUTHENTICATED_ANONYMOUSLY

  - path: /api/data
    method: [GET]
    handler: API.GET
    require: AUTH_REQUIRED

  - path: /api/data
    method: [POST]
    handler: API.POST
    require: AUTH_REQUIRED
