firewalls:
  main:
    pattern: "^/"
    auth:
      bearer:
        enabled: true

access:
  - path: /login
    require: IS_AUTHENTICATED_ANONYMOUSLY
  - path: /
    require: IS_AUTHENTICATED_ANONYMOUSLY
  - path: /api/*
    require: AUTH_REQUIRED
