firewalls:
  main:
    pattern: "^/"
    auth:
      bearer:
        enabled: true

access:
  - path: /login
    require: IS_AUTHENTICATED_ANONYMOUSLY
  - path: /public/*
    require: IS_AUTHENTICATED_ANONYMOUSLY
  - path: /admin/*
    require: ROLE_admin
  - path: /*
    require: AUTH_REQUIRED
