firewalls:
  main:
    pattern: "^/"
    auth:
      cookie:
        name: "SESSION_ID"

access:
  - path: /login
    require: IS_AUTHENTICATED_ANONYMOUSLY
  - path: /admin
    require: ROLE_admin
  - path: /*
    require: AUTH_REQUIRED
